export const useStyle = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    padding: "24px",
    background: "linear-gradient(135deg, #667eea 0%, #9785a8ff 100%)",
  },
  card: {
    width: "100%",
    maxWidth: 420,
    padding: "40px",
    borderRadius: "16px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.2)",
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  title: {
    fontWeight: 700,
    fontSize: "2rem",
    textAlign: "center",
    marginBottom: "24px",
    color: "#333",
  },
  button: {
    padding: "12px 0",
    borderRadius: "8px",
    backgroundColor: "#667eea",
    color: "#fff",
    fontWeight: 600,
    fontSize: "1rem",
    border: "none",
    cursor: "pointer",
    transition: "all 0.3s ease",
    textTransform: "uppercase",
  },
  buttonHover: {
    backgroundColor: "#5a67d8",
  },
  errorText: {
    marginTop: "8px",
    textAlign: "center",
    color: "#f44336",
    fontSize: "0.9rem",
    fontWeight: 500,
  },
  footerText: {
    marginTop: "16px",
    fontSize: "0.875rem",
    textAlign: "center",
    color: "#555",
  },
  input: {
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #ccc",
    fontSize: "1rem",
    width: "100%",
    outline: "none",
    transition: "all 0.3s ease",
  },
  inputFocus: {
    borderColor: "#667eea",
    boxShadow: "0 0 5px rgba(102, 126, 234, 0.5)",
  },
};
